### ISSUE TITLE
Migrate eis-dev.soe.ucsc.edu PDF links to elsewhere

### ISSUE THREAD

**Issue by mkremins** [ExpressiveIntelligence/expressiveintelligence.github.io#4]
From an email discussion I had with Noah:

> One thing we will want to fix sooner is that all the PDF URLs currently point to the eis-dev site, which I suspect BSOE will do away with once we say we’re not planning to use Drupal  :-)

I've found alternative links for some of the more recent publications (typically pointing at either the official publication location or an author's personal site), but we may want to rehost many of them either here (in this repository) or elsewhere.

**Comment by devibri** [comment]
Migrated all papers from eis-dev website to this github repo (/papers/nameofpaper.pdf) and updated links on Publications page.
